language: php
php:
  - 7.0
  - 7.1
  - nightly
services:
  - mysql
install:
  composer install
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script:
  - bin/robo opencart:setup
  - bin/phpunit --testsuite catalog-tests
  - bin/phpunit --testsuite admin-tests
